- docs/rules/require-expect.md
- index.js
- lib/rules/require-expect.js
- tests/lib/rules/require-expect.js
I've been working on a rule that advises when `assert.expect(n)` should be used in a test. The goal is to avoid issues where developers write assertions that are mistakenly never called.  Do you think this would make a good addition to this project?
> Add use-expect rule

- package.json
On my machine this pattern wasn't being interpreted correctly. `npm test` was running all of the scripts in `./build`. In the documentation examples for Istanbul I noticed that excluded fileset patterns were quoted.
> Build: Quote excluded fileset pattern for istanbul

- lib/rules/require-expect.js
- tests/lib/rules/require-expect.js
> require-expect using "except-simple" config should only report one error per test

- README.md
- docs/rules/no-identical-names.md
- index.js
- lib/rules/no-identical-names.js
- tests/lib/rules/no-identical-names.js
This PR implements a `no-identical-names` rule similar to https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-identical-title.md but for QUnit.
Resolves #56 
/cc @platinumazure
> Add "no-identical-names" rule

- docs/rules/no-assert-equal.md
Seems to render as literal `#Forbid` without the space.
> Docs: Fix heading syntax for no-assert-equal

- docs/rules/no-only.md
- lib/rules/no-only.js
- lib/utils.js
- tests/lib/rules/no-only.js
Fixes https://github.com/platinumazure/eslint-plugin-qunit/issues/72
@platinumazure I'm no eslint expert, but this seems to pass all the tests. Let me know if there's more I need to do
> Improve no-only rule to detect only() module.only() and QUnit.module.only()

- README.md
- docs/rules/no-assert-ok.md
- index.js
- lib/rules/no-assert-ok.js
- lib/utils.js
- tests/lib/rules/no-assert-ok.js
@platinumazure here's my attempt at implementing #77.
Apologies for this not being super polished, but I wanted to have something out to make sure we were on the same page.
A few notes:
1) The general idea behind this is to provide a function (`createAssertionCheck` -- still thinking of a better name) that can look for usages of assertions (global or against the local `assert` object);
2) For example, based on the above `no-assert-equal` could for example be refactored as:
```
// metadata ...
meta: {
// ...
messages: {
unexpectedGlobalEqual: "Unexpected equal. Use strictEqual, deepEqual, or propEqual.",
unexpectedAssertEqual: "Unexpected {{assertVar}}.equal. Use {{assertVar}}.strictEqual, {{assertVar}}.deepEqual, or {{assertVar}}.propEqual."
},
// ...
},
create: …
```
> Implement new rule `no-assert-ok`

- README.md
- docs/rules/no-skip.md
- index.js
- lib/rules/no-skip.js
- lib/utils.js
- tests/lib/rules/no-skip.js
Similar to `no-only` (and largely copied from), this rule prevents the use of `skip` in tests. As noted in the readme:
> `QUnit.skip` is useful to mark a test as skipped. This should be preferred over commenting out the test. However, leaving tests skipped in perpetuity is a bad practice, as the test ceases to provide any use in ensuring correctness of your code. Skipping tests should be done sparingly.
It's debatable whether this should be part of recommended or not. I'm open to discussions.
> New rule: no-skip

- lib/rules/no-arrow-tests.js
- tests/lib/rules/no-arrow-tests.js
Fixer adapted from eslint-plugin-mocha (MIT)
> Add a fixer for no-arrow-tests

- README.md
- docs/rules/no-loose-assertions.md
- index.js
- lib/rules/no-assert-ok.js
- lib/rules/no-loose-assertions.js
- lib/utils.js
- tests/lib/rules/no-loose-assertions.js
As discussed in https://github.com/platinumazure/eslint-plugin-qunit/issues/77#issuecomment-589258915 and https://github.com/platinumazure/eslint-plugin-qunit/pull/78#issue-378429556 introducing the new `no-loose-assertions` rule which allows forbids the usage of assertions like `equal`, `ok`, `notOk`.
This rule is supposed to replace [`no-assert-equal`](https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-assert-equal.md) and [`no-assert-ok`](https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-assert-ok.md) with one configurable rule.
@platinumazure please take a look and let me know what you think!
> New no-loose-assertions rule.

- lib/rules/literal-compare-order.js
- tests/lib/rules/literal-compare-order.js
This makes it much easier to adopt this rule. Changing the order of arguments does not cause any behavior change.
> Add autofixer to `literal-compare-order` rule

- lib/rules/no-ok-equality.js
- tests/lib/rules/no-ok-equality.js
I used this on my codebase to fix 100+ violations.
> Add autofixer to `no-ok-equality` rule

- lib/rules/no-compare-relation-boolean.js
- tests/lib/rules/no-compare-relation-boolean.js
Before this fix, this lint rule would not report any violations when a message was passed to the assertion function.
> Fix `no-compare-relation-boolean` rule to handle assertions with messages

- docs/rules/no-async-in-loops.md
- docs/rules/no-ok-equality.md
- docs/rules/resolve-async.md
- tests/index.js
This adds two initial tests for ensuring rule consistency. I plan to follow-up with additional tests soon.
Inspired by a similar suite of rule tests in [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember/blob/master/tests/rule-setup.js) and [ember-template-lint](https://github.com/ember-template-lint/ember-template-lint/blob/master/test/unit/rule-setup-test.js).
> Add tests to ensure rules have tests and basic rule doc

- docs/rules/literal-compare-order.md
- docs/rules/no-arrow-tests.md
- docs/rules/no-compare-relation-boolean.md
- docs/rules/no-ok-equality.md
- docs/rules/no-setup-teardown.md
- tests/index.js
ESLint rule docs provide this same exact notice. Example: https://eslint.org/docs/rules/no-extra-semi
Also adds a test to ensure rule docs correctly include the fixable notice.
A subsequent follow-up will be to indicate which rules are fixable in the README.md with the :wrench: icon.
> Add fixable notice to rule doc of autofixable rules

- package-lock.json
- package.json
No new lint scripts yet but this makes it easy to add additional lint scripts later (such as lint:docs, lint:package-json, etc).
> Add npm-run-all for running lint scripts

- docs/rules/assert-args.md
- docs/rules/literal-compare-order.md
- docs/rules/no-async-in-loops.md
- docs/rules/no-async-test.md
- docs/rules/no-commented-tests.md
- docs/rules/no-global-assertions.md
- docs/rules/no-global-expect.md
- docs/rules/no-global-module-test.md
- docs/rules/no-global-stop-start.md
- docs/rules/no-identical-names.md
- docs/rules/no-init.md
- docs/rules/no-jsdump.md
- docs/rules/no-ok-equality.md
- docs/rules/no-only.md
- docs/rules/no-qunit-push.md
- docs/rules/no-qunit-start-in-tests.md
- docs/rules/no-qunit-stop.md
- docs/rules/no-reassign-log-callbacks.md
- docs/rules/no-reset.md
- docs/rules/no-setup-teardown.md
- docs/rules/no-test-expect-argument.md
- docs/rules/no-throws-string.md
- docs/rules/require-expect.md
- docs/rules/resolve-async.md
- tests/index.js
ESLint rule docs provide this same exact notice. Example: https://eslint.org/docs/rules/no-extra-semi
Also adds a test to ensure rule docs correctly include the notice.
This is a follow-up to https://github.com/platinumazure/eslint-plugin-qunit/pull/106 where I added a fixable notice to rule docs.
> Add notices to each rule doc indicating which configuration enables the rule

- package-lock.json
- package.json
ESLint v6 and v7 have been out for a while.
The upcoming NPM v7 will also automatically install missing peer dependencies and we don't want it to be be installing old versions of ESLint due to this bug.
Fixes #112.
> Allow ESLint peer dependency to include v6 and v7

- .github/workflows/ci.yml
Let's see if this fixes the Coveralls issue in the CI action.
> Build: Update lcov location in coveralls action

- index.js
- tests/index.js
Fixes #122.
This makes it easier for consumers to use these configs without having to specify the plugin themselves.
> Add `qunit` plugin to configs

- README.md
- docs/rules/no-assert-equal-boolean.md
- index.js
- lib/rules/no-assert-equal-boolean.js
- tests/lib/rules/no-assert-equal-boolean.js
For enforcing usage of new `assert.true(...)` or `assert.false(...)` assertions.
> Add new rule `no-assert-equal-boolean`

- lib/rules/no-identical-names.js
- tests/lib/rules/no-identical-names.js
> Catch duplicate titles in ancestor modules in `no-identical-names` rule

- lib/rules/no-global-assertions.js
- lib/rules/no-global-expect.js
- lib/rules/no-global-module-test.js
- lib/rules/no-global-stop-start.js
- lib/utils.js
- package-lock.json
- package.json
- tests/lib/rules/no-global-assertions.js
- tests/lib/rules/no-global-expect.js
- tests/lib/rules/no-global-module-test.js
- tests/lib/rules/no-global-stop-start.js
Fixes #75.
Updates these rules to only detect true global usages of `module()`, `deepEqual()`, etc and not usages where these functions are imported or defined locally.
This is now a valid example whereas previously it had false positives:
```js
import { test } from 'ember-qunit';
import { module } from 'qunit';
module('foo', hooks => {
test('bar', function(assert) {
// ...
});
});
```
Makes use of the eslint-utils [ReferenceTracker](https://eslint-utils.mysticatea.dev/api/scope-utils.html#referencetracker-class) class.
* [no-global-assertions](https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-global-assertions.md)
* [no-global-expect](https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-global-expect.md)
* …
> Only detect true globals in `no-global-*` rules

- lib/rules/no-identical-names.js
- tests/lib/rules/no-identical-names.js
Significantly refactors/simplifies logic.
Fixes #130.
> Allow tests with identical names in different modules in `no-identical-names` rule

- README.md
Helpful for calling out clearly the current package version and linking to the package on the NPM website.
> Add NPM version badge to README

- lib/rules/no-identical-names.js
- tests/lib/rules/no-identical-names.js
The problem was that `reverse` was performing an in-place reversal of the modules array every time it was called, when it was only intended for assisting with finding the last matching element and was not supposed to modify the array.
Fixes #142.
> Fix false positive for tests in different modules in `no-identical-names` rule

- lib/rules/no-identical-names.js
- tests/lib/rules/no-identical-names.js
This PR fixes the detection of test-less modules. A module is considered test-less if it has no tests nested inside it. Sibling tests that come after a test-less module are considered part of the module.
Fixes this test case:
```js
module('A', {});
test('foo', function () {});
module('B', {});
test('foo', function () {});
```
CC: @asapach
Related to #143.
> Fix detection of test-less modules in `no-identical-names` rule

- index.js
There's an unreleased commit that switched the plugin to use requireindex for loading the rules: https://github.com/platinumazure/eslint-plugin-qunit/commit/d3e0440301971feab59505f3fa8cd6a6434bb77a. I noticed this broke the plugin for me.
eslint-plugin-qunit is included in a config in another linting plugin of mine. As a result, the requireindex call was checking the wrong current directory for lib/rules.
```
Oops! Something went wrong! :(
ESLint: 7.10.0
Error: Failed to load plugin 'qunit' declared in '.eslintrc.js » plugin:my-plugin/my-config': Cannot find module 'my-home-folder/eslint-plugin-qunit/lib'
Require stack:
- my-home-folder/eslint-plugin-qunit/node_modules/requireindex/index.js
- my-home-folder/eslint-plugin-qunit/index.js
- …
```
> Fix `requireindex` usage to use correct directory

- .github/workflows/ci.yml
- package.json
ESLint 6 has been out since 2019-06 and requiring it will enable us to use more sophisticated eslint features.
https://eslint.org/docs/user-guide/migrating-to-6.0.0
This can be merged as part of the V6 release: #114
> Require eslint 6+ as peer dependency

- .github/workflows/ci.yml
- package.json
Node 13 is an odd-numbered version that is end-of-life.
This can be merged as part of the V6 release: #114
> Drop Node 13 support

- docs/rules/no-negated-ok.md
- lib/rules/no-negated-ok.js
- tests/lib/rules/no-negated-ok.js
This can be merged as part of the V6 release: #114 (V6 will require QUnit 2+ which has `notOk`).
> Update `fixToNotOk` rule option default to true in `no-negated-ok` rule

- docs/rules/no-compare-relation-boolean.md
- lib/rules/no-compare-relation-boolean.js
- tests/lib/rules/no-compare-relation-boolean.js
This can be merged as part of the V6 release: #114 (V6 will require QUnit 2+ which has `notOk`).
> Update `fixToNotOk` rule option default to true in `no-compare-relation-boolean` rule

- docs/rules/require-expect.md
- index.js
- lib/rules/require-expect.js
- tests/lib/rules/require-expect.js
Why? Because the `recommended` config was manually enabling this rule with the `expect-simple` behavior, so we might as well make that the default behavior of the rule to reduce confusion and improve consistency.
This can be merged as part of the V6 release: #114.
> Update `require-expect` rule to default to `expect-simple` option

- README.md
- docs/rules/no-async-test.md
- docs/rules/no-global-assertions.md
- docs/rules/no-global-expect.md
- docs/rules/no-global-module-test.md
- docs/rules/no-global-stop-start.md
- docs/rules/no-init.md
- docs/rules/no-jsdump.md
- docs/rules/no-qunit-push.md
- docs/rules/no-qunit-start-in-tests.md
- docs/rules/no-qunit-stop.md
- docs/rules/no-reassign-log-callbacks.md
- docs/rules/no-reset.md
- docs/rules/no-setup-teardown.md
- docs/rules/no-test-expect-argument.md
- docs/rules/no-throws-string.md
- index.js
- scripts/update-rules.js
- tests/index.js
This can be merged as part of the V6 release: #114.
It would be easiest if we merged some other changes first then rebased this PR:
> Merge `two` config into `recommended` config

- docs/rules/require-object-in-propequal.md
`deepStrictEqual` does not exist in qunit (it only exists in Node). `deepEqual` is strict in qunit.
https://api.qunitjs.com/assert/deepEqual/
> Fix typo of `deepEqual` assert name in `require-object-in-propequal` rule doc

- lib/rules/no-hooks-from-ancestor-modules.js
- tests/lib/rules/no-hooks-from-ancestor-modules.js
Instead of flagging the entire CallExpression node as shown here which could be dozens of lines long:
```js
hooks.beforeEach(function() {
// potentially dozens of lines of code
});
```
...we can just flag the `hooks.beforeEach` callee containing the `hooks` variable that is coming from the wrong module.
@raycohen
> Only flag identifier node instead of entire call expression in `no-hooks-from-ancestor-modules` rule

- lib/rules/no-assert-equal.js
- tests/lib/rules/no-assert-equal.js
Suggests 3 fixes that can be automatically applied for violations of this rule.
https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions
https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-assert-equal.md
> Add automatic suggestions for `no-assert-equal` rule

- .eslintrc.json
- docs/rules/no-assert-ok.md
- docs/rules/no-early-return.md
- docs/rules/no-global-assertions.md
- docs/rules/no-loose-assertions.md
- docs/rules/no-nested-tests.md
- docs/rules/no-qunit-stop.md
- docs/rules/require-expect.md
- package-lock.json
- package.json
This applies our JavaScript linting to the JavaScript code samples in the markdown documentation files.
Initially, this is just focused on fixing the syntax errors and a few one-off violations. I have disabled other rules that had many violations. There are some autofixable stylistic rules we can follow-up to fix to ensure code sample formatting consistency.
> Add eslint-plugin-markdown for JavaScript code samples in documentation

- .eslintrc.json
- docs/rules/no-assert-ok.md
- docs/rules/no-async-module-callbacks.md
- docs/rules/no-hooks-from-ancestor-modules.md
- docs/rules/no-loose-assertions.md
Autofixed.
I think we should switch to prettier eventually though.
I tried autofixing other stylistic rules but they caused syntax errors oddly.
https://eslint.org/docs/rules/indent
> Enable `indent` rule in markdown JS code samples

- lib/utils.js
- tests/lib/rules/assert-args.js
- tests/lib/rules/no-assert-logical-expression.js
- tests/lib/rules/no-conditional-assertions.js
- tests/lib/rules/no-global-assertions.js
Fixes #169. Adds the new boolean assertions (`true` and `false`) to our list of assertions so that they will be taken into account by several rules. Adds test cases to several rules.
> Ensure boolean assertions are not missed by several rules

- docs/rules/no-ok-equality.md
- lib/rules/no-ok-equality.js
- tests/lib/rules/no-ok-equality.js
This adds a new option `checkBooleanAssertions` to the rule [no-ok-equality](https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-ok-equality.md).
The boolean assertions `true`/`false` are very similar to the `ok`/`notOk` assertions that are already checked by the rule.
Disallows and autofixes assertions like:
```js
assert.true(foo === 1);
assert.false(foo !== 1);
```
We can enable the `checkBooleanAssertions` option by default in the next major release.
Fixes #171.
> Add `checkBooleanAssertions` option to `no-ok-equality` rule

- .eslintrc.json
- .github/workflows/ci.yml
- package-lock.json
- package.json
- tests/index.js
I refactored the index.js test structure a bit to simplify things and help address these two rules:
* [mocha/no-nested-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-nested-tests.md) (we had `describe` nested inside `it`)
* [mocha/no-setup-in-describe](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-setup-in-describe.md) (doesn't like function calls or member expressions inside `describe`)
Note: for our ESLint 6 CI test, we have to use an older version of eslint-plugin-mocha that is still compatible with ESLint 6.
https://github.com/lo1tuma/eslint-plugin-mocha
> Add eslint-plugin-mocha

- lib/rules/no-assert-equal.js
- tests/lib/rules/no-assert-equal.js
The rule should disallow the global `equal` under the assumption that this is the QUnit assertion. But a custom `equal` function that is locally defined or imported should be ignored.
Fixes #182.
> Fix false positive with unrelated `equal` function in `no-assert-equal` rule

- README.md
- scripts/update-rules.js
Give config/fixable emojis separate columns.
Matches the format in: https://github.com/sindresorhus/eslint-plugin-unicorn#rules
> Improve columns in README rules table

- lib/rules/no-assert-equal.js
The change to require suggestable rules to have `meta.hasSuggestions` has been accepted and mentioned in the blog post for the upcoming ESLint 8 breaking changes. So we should adopt this change now to ensure we are compatible with ESLint 8 as soon as possible. The old property `meta.docs.suggestion` was unused anyway.
https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0#rules-with-suggestions-now-require-the-metahassuggestions-property
> Use `meta.hasSuggestions` for suggestable rules to prepare for ESLint 8

- .eslintrc.json
We can use the `all` config to be a bit more aggressive about picking up all the rules in [eslint-plugin-eslint-plugin](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin). This simplifies our linting config and ensures we don't miss out on new rules. In the rare event that we don't like a future rule that gets added to this plugin, we can simply disable the specific rule to opt-out.
> Switch to `all` config from eslint-plugin-eslint-plugin rules internally

- README.md
- docs/rules/no-assert-equal.md
- index.js
[no-assert-equal](https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-assert-equal.md)
Fixes #164.
Part of v7 release (https://github.com/platinumazure/eslint-plugin-qunit/projects/1, https://github.com/platinumazure/eslint-plugin-qunit/issues/175).
> Breaking: Add `no-assert-equal` to `recommended` config

- docs/rules/no-compare-relation-boolean.md
- docs/rules/no-negated-ok.md
- docs/rules/no-ok-equality.md
- lib/rules/no-compare-relation-boolean.js
- lib/rules/no-negated-ok.js
- lib/rules/no-ok-equality.js
- tests/lib/rules/no-compare-relation-boolean.js
- tests/lib/rules/no-negated-ok.js
- tests/lib/rules/no-ok-equality.js
* The [notOk](https://api.qunitjs.com/assert/notOk/) assertion was added in QUnit 1.18, and we only support QUnit 2+, so we can enable/remove the `fixToNotOk` option so that rules can assume `notOk` is available
* The [true](https://api.qunitjs.com/assert/true/) and [false](https://api.qunitjs.com/assert/false/) boolean assertions were added in QUnit 2.11, and enabling/removing the `checkBooleanAssertions` option will subject these assertions to additional linting
We can remove these options to simplify the rules and ease the maintenance burden.
Removed these options together to avoid conflicts since a lot of the code overlaps.
Fixes #190, fixes #195. Part of the v7 release (#175).
> Breaking: Remove `fixToNotOk` and `checkBooleanAssertions` rule options

- docs/rules/no-loose-assertions.md
- docs/rules/no-ok-equality.md
- tests/index.js
Add test to ensure:
1. Any rule with options has a `## Options` section in its rule doc.
2. Any named rule options are mentioned in the rule doc.
Based on the same test I wrote here: https://github.com/ember-cli/eslint-plugin-ember/blob/4f26c0bc7e34400007e02939a9c6e183078a3e87/tests/rule-setup.js#L111
> Ensure rule docs mention all rule options

- lib/utils.js
- tests/lib/rules/assert-args.js
- tests/lib/rules/literal-compare-order.js
- tests/lib/rules/no-assert-equal-boolean.js
- tests/lib/rules/no-assert-equal.js
- tests/lib/rules/no-assert-logical-expression.js
- tests/lib/rules/no-assert-ok.js
- tests/lib/rules/no-async-in-loops.js
- tests/lib/rules/no-compare-relation-boolean.js
- tests/lib/rules/no-conditional-assertions.js
- tests/lib/rules/no-early-return.js
- tests/lib/rules/no-loose-assertions.js
- tests/lib/rules/no-negated-ok.js
- tests/lib/rules/no-ok-equality.js
- tests/lib/rules/no-throws-string.js
- tests/lib/rules/require-expect.js
- tests/lib/rules/require-object-in-propequal.js
- tests/lib/rules/resolve-async.js
> Fix: Check for arrow functions in utils.getAssertContextNameForTest

- lib/utils.js
- tests/lib/rules/assert-args.js
- tests/lib/rules/literal-compare-order.js
- tests/lib/rules/no-arrow-tests.js
- tests/lib/rules/no-assert-equal-boolean.js
- tests/lib/rules/no-assert-equal.js
- tests/lib/rules/no-assert-logical-expression.js
- tests/lib/rules/no-async-in-loops.js
- tests/lib/rules/no-compare-relation-boolean.js
- tests/lib/rules/no-early-return.js
- tests/lib/rules/no-negated-ok.js
- tests/lib/rules/no-ok-equality.js
- tests/lib/rules/no-throws-string.js
- tests/lib/rules/require-expect.js
Fixes #215. Uses the same fix that we used to fix https://github.com/platinumazure/eslint-plugin-qunit/issues/161.
> Handle adding TypeScript type to `this` parameter in `test` hook in many rules

- docs/rules/no-only.md
- docs/rules/no-skip.md
- lib/utils.js
- tests/lib/rules/no-only.js
- tests/lib/rules/no-skip.js
The isQunitMethod utils function will be updated to make the `test.\<someQunitMethod\>()` pattern detectable. The `no-skip` and `no-only` rules will also be updated according to this new detectable test case
BEFORE
```
1) no-skip
invalid
test.skip('Name', function() { });:
AssertionError [ERR_ASSERTION]: Should have 1 error but had 0: []
+ expected - actual
-0
+1
```
AFTER
```
✔ test.skip('Name', function() { });
```
> Update "isQunitMethod" utils function to handle "test.<SomeQunitMethod>" test cases

- docs/rules/no-hooks-from-ancestor-modules.md
- lib/rules/no-hooks-from-ancestor-modules.js
- tests/lib/rules/no-hooks-from-ancestor-modules.js
Fixes https://github.com/platinumazure/eslint-plugin-qunit/issues/230.
> Fix: Allow for third parameter in no-hooks-from-ancestor-modules

- lib/rules/no-compare-relation-boolean.js
- tests/lib/rules/no-compare-relation-boolean.js
My editor runs eslint on every change to the source file. When I type `assert.strictEqual(`, the editor autofills the closing paren. Then eslint crashes on the `no-compare-relation-boolean` rule with the error:
> TypeError: Cannot read properties of undefined (reading 'type')
> Fix no-compare-relation-boolean error when passing <2 args

- lib/rules/no-hooks-from-ancestor-modules.js
- lib/rules/no-only.js
- lib/rules/no-skip.js
- tests/lib/rules/no-skip.js
Fixing some lint violations detected by my WIP PR to update [eslint-plugin/no-missing-placeholders](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/main/docs/rules/no-missing-placeholders.md) and [eslint-plugin/no-unused-placeholders](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/main/docs/rules/no-unused-placeholders.md) to handle placeholders in messageIds:
* https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/252
```
lib/rules/no-hooks-from-ancestor-modules.js
31:43  error  The placeholder {{hookName}} does not exist      eslint-plugin/no-missing-placeholders
31:43  error  The placeholder {{invokedMethodName}} is unused  eslint-plugin/no-unused-placeholders
lib/rules/no-only.js
27:26  error  The placeholder {{callee}} is unused …
```
> fix: incorrectly-used violation message placeholders

- .github/workflows/ci.yml
It looks like CI is currently failing because we upgrade npm during CI to a version no longer compatible with Node 12.
```
ERROR: npm v9.1.1 is known not to run on Node.js v12.22.12. You'll need to
upgrade to a newer Node.js version in order to use this version of npm. This
version of npm supports the following node versions: `^14.17.0 || ^1[6](https://github.com/platinumazure/eslint-plugin-qunit/actions/runs/3461679329/jobs/5779590138#step:5:7).13.0 ||
>=18.0.0`. You can find the latest version at [https://nodejs.org/.](https://nodejs.org/)
```
I don't know why we need to upgrade npm. Most CI scripts do not need to upgrade npm.
Upgrade step originally added here: https://github.com/platinumazure/eslint-plugin-qunit/commit/432744a177f636cfa5ce9202292ff12cfd9b9359
> chore: remove npm upgrade step from CI

- lib/rules/no-hooks-from-ancestor-modules.js
- tests/lib/rules/no-hooks-from-ancestor-modules.js
> Update: no-hooks-from-ancestor-modules works with arrow module callbacks

- lib/rules/no-hooks-from-ancestor-modules.js
- tests/lib/rules/no-hooks-from-ancestor-modules.js
This bug was caused by #267 which was attempting to fix #246.
The previous fix update the `FunctionExpression` check in one place but not the other.
CC: @platinumazure @bretjb
> Fix false positives with arrow functions in `no-hooks-from-ancestor-modules` rule

- RELEASE.md
release-it expects the GitHub access token to be set in the `GITHUB_TOKEN` environment variable.
`GITHUB_AUTH` is a far-less-common name for this variable that some repos manually choose.
https://github.com/release-it/release-it/blob/master/docs/github-releases.md#automated
> Docs: Correct GitHub access token variable name for releases

- .github/workflows/ci.yml
- package-lock.json
- package.json
BREAKING CHANGE
These are end-of-life: https://github.com/nodejs/release#release-schedule
Part of https://github.com/platinumazure/eslint-plugin-qunit/issues/222.
> Drop support for Node 12, 14, 17, 19

- docs/rules/require-expect.md
- lib/rules/require-expect.js
- tests/lib/rules/require-expect.js
Discussion here: https://github.com/platinumazure/eslint-plugin-qunit/issues/222#issuecomment-1031800401
Part of https://github.com/platinumazure/eslint-plugin-qunit/issues/222.
> Change `require-expect` rule default option to `never-except-zero`

- package.json
The `eslint` preset doesn't work well and doesn't appear to have any configurability.
I am switching to the `conventionalcommits` preset which is more popular and reliable.
I enabled the common prefixes/sections we use with it, while intentionally excluding "upgrade" which would add a lot of dependabot spam to the changelog.
This preset appears to do a better job with:
* Picking the right version to use for the release based on semver (overridable with `npm run release -- --i major`)
* Grouping the commits into sections for the changelog
* I also opened https://github.com/release-it/conventional-changelog/issues/63 because I was hoping we could manually edit the changelog when needed
I did a dry-run to test and the results look better.
More info:
* …
> Tweak release-it

- docs/rules/require-expect.md
Follow-up to #375.
I missed one update to the doc.
> Fix default in doc for `require-expect` rule

- README.md
- docs/rules/no-ok-equality.md
- index.js
- lib/rules/no-ok-equality.js
- package-lock.json
- package.json
Note that I have only added these auto-generated rule doc option lists to rules with simple object-based options. Other types of options (enums/arrays/etc) aren't supported yet.
These features shipped in:
* https://github.com/bmish/eslint-doc-generator/releases/tag/v1.5.0
* https://github.com/bmish/eslint-doc-generator/pull/480
> docs: auto-generate readme configs list and some rule doc options lists with eslint-doc-generator

- .github/workflows/ci.yml
Noticed that a bunch of the upgrade PRs are failing with the occasional coveralls "build is closed" error. So I configured for parallel coveralls jobs for now. (Maybe running coverage on only latest Node would be better, though.)
Reference: https://docs.coveralls.io/parallel-builds
> ci: Use parallel coveralls config

- .github/workflows/ci.yml
Needed to switch `path-to-lcov` option to `file`. Hopefully this will pass CI and I can merge this right away.
> upgrade: coverallsapp/github-action@v2

- README.md
- index.js
Fixes this comment:
* https://github.com/platinumazure/eslint-plugin-qunit/pull/443#issuecomment-1937479754
Context:
* https://github.com/bmish/eslint-doc-generator/issues/506
* https://github.com/eslint/eslint/issues/17842
This reverts part of:
* https://github.com/platinumazure/eslint-plugin-qunit/pull/416
ESLint no longer allows arbitrary properties like `description` on configs.
Fixes #478.
> fix: remove disallowed description property from config

- lib/rules/no-assert-equal.js
- lib/rules/no-global-assertions.js
- lib/rules/no-global-expect.js
- lib/rules/no-global-module-test.js
- lib/rules/no-global-stop-start.js
Fixes https://github.com/platinumazure/eslint-plugin-qunit/issues/499
I verified all tests pass under eslint v9, but also maintained backward compatibility. Tests require updates that are not v8 compatible so I have another branch where I tested against v9. https://github.com/LucasHill/eslint-plugin-qunit/tree/test_fixes_for_eslint_v9
A future improvement would be to run this plugin against multiple eslint versions, as I can't include the test changes without committing to only testing on v9. If this is desired, I can bring those changes into this branch and the project will be upgraded to test against v9.
I do think it could be worth releasing this in a patch version as the changes are minimal, and intentionally backwards compatible. I know there are plans brewing for the v9 version of …
> Fix eslint v9 compatibility issues

- eslint.config.js
- package-lock.json
- package.json
These violations got through to master somehow:
- https://github.com/qunitjs/eslint-plugin-qunit/pull/537
Release notes:
- https://github.com/eslint-community/eslint-plugin-eslint-plugin/releases/tag/v6.0.0
> chore: fix violations of eslint-plugin-eslint-plugin v6

- index.js
This was failing when the path ended with `/dist` since it was checking for `/dist/`. I've updated it so the slashes don't matter as those can be operating system dependent anyway.
> fix: crash when loading loading package.json in index.js

- package.json
This was causing low coverage numbers.
> chore: ignore dist/ for nyc test coverage
