qunitjs/eslint-plugin-qunit

docs/rules/require-expect.md
lib/rules/require-expect.js
tests/lib/rules/require-expect.js

New: "never" and "never-except-zero" options for require-expect rule

---

README.md
scripts/update-rules.js

Fix broken rules link in README

---

.github/workflows/ci.yml
.travis.yml
README.md
package.json

Coveralls info: https://github.com/marketplace/actions/coveralls-github-action

Switch from Travis to Github Actions

---

lib/rules/no-identical-names.js
tests/lib/rules/no-identical-names.js

Fix false positives with nested modules in `no-identical-names` rule 

---

.markdownlint.json
.markdownlintignore
README.md
docs/rules/assert-args.md
docs/rules/literal-compare-order.md
docs/rules/no-assert-ok.md
docs/rules/no-loose-assertions.md
docs/rules/no-nested-tests.md
docs/rules/require-expect.md
package-lock.json
package.json

A few examples of what was fixed:
* Fixes wrong header sizes
* Ensures codeblocks have language specified
* Newline lists lists
* Consistent spacing / list types
https://github.com/igorshubovych/markdownlint-cli

Add markdownlint

---

README.md
scripts/update-rules.js

Add rule descriptions to rules table in README

---

package-lock.json
package.json

all-contributors-cli, eslint, markdownlint-cli, mocha, outdent, semver

Upgrade: devDependencies

---

README.md
docs/rules/no-async-module-callbacks.md
lib/rules/no-async-module-callbacks.js
tests/lib/rules/no-async-module-callbacks.js

New rule: no-async-module-callbacks (#147)

---

tests/lib/rules/require-object-in-propequal.js

Chore: Uncomment ES2020 tests in require-object-in-propequal

---

.eslintrc.json
package-lock.json
package.json

Best practices around eslint-disable comments.
https://github.com/mysticatea/eslint-plugin-eslint-comments

Add eslint-plugin-eslint-comments

---

lib/rules/no-hooks-from-ancestor-modules.js
package-lock.json
package.json
tests/lib/rules/no-hooks-from-ancestor-modules.js

Handle typed `this` callback argument in `no-hooks-from-ancestor-modules` rule

---

CHANGELOG.md
docs/rules/no-conditional-assertions.md
docs/rules/require-expect.md
lib/rules/no-loose-assertions.js
tests/lib/rules/no-early-return.js
tests/lib/rules/require-expect.js

Used `cspell` to check: https://www.npmjs.com/package/cspell

Fix various typos

---

README.md
docs/rules/no-arrow-tests.md
index.js

Breaking: Remove no-arrow-tests from recommended config

---

.eslintrc.json
.github/workflows/ci.yml
lib/rules/no-reassign-log-callbacks.js
package-lock.json
package.json
tests/lib/rules/no-assert-equal.js
tests/lib/rules/no-global-assertions.js
tests/lib/rules/no-global-expect.js
tests/lib/rules/no-global-module-test.js
tests/lib/rules/no-global-stop-start.js
tests/lib/rules/no-hooks-from-ancestor-modules.js

Breaking: Drop support for old Node and ESLint versions

---

package.json

Just in case. Ensure people can find this plugin.
https://eslint.org/docs/developer-guide/working-with-plugins#share-plugins

Add `eslint-plugin` keyword in package.json

---

.github/workflows/ci.yml

Add Node 18 to CI

---

.gitignore
package.json

Quick PR to speed up ESLint with the `--cache` flag.

Add caching to ESLint

---

.github/workflows/ci.yml
package.json

feat!: Require eslint@^8.38, drop support for eslint@7.x

---

CHANGELOG.md
package-lock.json
package.json

I don't have permission to push directly to main so I am opening a PR for this.

Release 8.1.1

---

package.json

Follow-up to: 
- https://github.com/qunitjs/eslint-plugin-qunit/pull/571

fix: entrypoint
